### ISSUE TITLE
Model Deployment

### ISSUE THREAD

**Issue by ASM313** [ASM313/News-Sorting#11]
-     Deploy the trained model into production or integrate it into existing systems.
-     Implement necessary infrastructure for serving predictions (e.g., APIs, microservices).
-     Monitor model performance and retrain periodically to maintain accuracy over time.

**Comment by ASM313** [comment]
### Tasks to perform

- Create API's
- Create Front end

**Comment by Atiq-Ur-Rehman7** [comment]
.

**Comment by Atiq-Ur-Rehman7** [comment]
done
