### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by ASM313** [ASM313/News-Sorting#8]
### Pre process your data including: 

- Clean the text data by removing noise (e.g., HTML tags, special characters).
- Tokenize the text into words or subword units.
- Normalize the text (e.g., lowercase conversion, stemming, lemmatization).
- Handle data imbalances or missing values if applicable.

**Comment by Atiq-Ur-Rehman7** [comment]
Data preprocessing will be done in #5 Data Transformation.
